name: driving_app_ios
description: A new Flutter project.
publish_to: 'none'

# 補上圖五要求的 SDK 限制
environment:
  sdk: '>=3.0.0 <4.0.0' # 放大相容範圍

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^10.1.0
  flutter_tts: ^3.8.5
  audio_session: ^0.1.18
  csv: ^6.0.0

flutter:
  uses-material-design: true
  # 合併所有的 assets 到這裡
  assets:
    - assets/camera_data.csv
